### ISSUE TITLE
[Bug]: При нажатии на кнопку скачивания видео, в консоль выводится ошибка

### ISSUE THREAD

**Issue by mrksbgg** [IvanSavoskin/more-boosty-remastered#29]
### Description

При нажатии на кнопку скачивания видео, в консоль выводится ошибка: https://i.imgur.com/X38Mell.png

### Reproduce

1. Открыть пост с видео (например https://boosty.to/zako/posts/73f5fb0d-a353-4567-b149-fa46d7d44ce8?share=post_link)
2. Нажать скачать
3. Открыть консоль дабы увидеть ошибку

### Expected behavior

Видео должно скачиваться после нажатия на кнопку скачивания видео

### Version

1.2.0

### Browser

Chrome

**Comment by IvanSavoskin** [comment]
@mrksbgg Добрый день
Сейчас попробовал на видео из описания - модальное окно корректно открывается и видео скачивается.
Возможно это была какая-то временная проблема на стороне Бусти

**Comment by mrksbgg** [comment]
Проблема была решена, нужно было войти в аккаунт на бусти
