### ISSUE TITLE
[Bug]: Пропала возможность скачивания аудио

### ISSUE THREAD

**Issue by Windjammer173** [IvanSavoskin/more-boosty-remastered#32]
### Description

Если не ошибаюсь, в первом расширении была кнопка для скачивания аудио. Потом она стала невидимой, но я знал, что если кликнуть сверху над опубликованным аудио, то пойдёт скачивание. Теперь же, никакой кнопки по-прежнему не видно, но и кликать вокруг аудио бесполезно - скачивание не начинается, как будто бы такой функции и нету.

### Reproduce

Кнопки для скачивания аудио нет. Кликаю по путому пространству над и под опубликованным аудио, но скачивание не происходит

### Version

1.2.0

### Browser

Chrome

### Additional Info

мой браузер, уточню Google Chrome Версия 131.0.6778.13 (Официальная сборка), beta (64 бит)
пример для скачивания, вот — https://boosty.to/agitprop/posts/099c5982-5c67-44a5-9d2e-c34244dbc85a

**Comment by IvanSavoskin** [comment]
Добрый день @Windjammer173 
Проблема произошла из-за того, что Boosty полностью переделали аудио плееры. Я подготовил изменения. В следующем релизе скачивание будет доступно, но не так удобно как раньше
На счет проблемы с тем, что иконка не отображается - я слышу впервые. Если после релиза 1.2.1 будет также, то прошу создать на это отдельный баг

**Comment by IvanSavoskin** [comment]
Обновление отправлено на проверку Chrome Web Store и станет доступно в ближайшие пару дней

**Comment by Windjammer173** [comment]
Текущая версия 1.2.1
Кнопка для скачивания появилась — скачивание работает.
Спасибо!
