### ISSUE TITLE
Sometimes playback speed is reset

### ISSUE THREAD

**Issue by rnyPlanet** [IvanSavoskin/more-boosty-remastered#4]
![image](https://github.com/user-attachments/assets/b408e027-882d-4473-9f82-883fba52d802)

If I understand correctly - it's here
https://github.com/IvanSavoskin/more-boosty-remaster/blob/master/source/content/playerChanges.js#L472

**Comment by IvanSavoskin** [comment]
Hello!
Try to build the extension from the branch https://github.com/IvanSavoskin/more-boosty-remaster/tree/develop
Build instructions https://github.com/IvanSavoskin/more-boosty-remaster/tree/develop?tab=readme-ov-file#%D1%81%D0%B1%D0%BE%D1%80%D0%BA%D0%B0-%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B2%D1%80%D1%83%D1%87%D0%BD%D1%83%D1%8E

At the moment I am editing the extension for my own use: perhaps in the future I will upload a corrected version version also in Chrome WebStore

**Comment by rnyPlanet** [comment]
> Try to build the extension from the branch https://github.com/IvanSavoskin/more-boosty-remaster/tree/develop 

yes, i built on the develop branch.  Do you have this problem with speed reduction?

**Comment by IvanSavoskin** [comment]
> > Try to build the extension from the branch https://github.com/IvanSavoskin/more-boosty-remaster/tree/develop
> 
> yes, i built on the develop branch. Do you have this problem with speed reset?

Hmmm, no, I haven't seen a problem like this, but I'll check and see if I can find anything. And what actions cause the reset and this error? Just when watching a video?

**Comment by rnyPlanet** [comment]
> Hmmm, no, I haven't seen a problem like this, but I'll check and see if I can find anything. And what actions cause the reset and this error? Just when watching a video?

Yes, just when watching a video, it doesn't matter what speed.
I'll try to re-produce it on a clean browser later.

**Comment by IvanSavoskin** [comment]
Hi @rnyPlanet!
This issue should not be in the release https://github.com/IvanSavoskin/more-boosty-remaster/releases/tag/v1.0.0
Please check if this is true.

**Comment by IvanSavoskin** [comment]
Link to extension https://chromewebstore.google.com/detail/more-boosty-remaster/fkgamejmaiikhojcmjoaaegdimdalnom?authuser=0&hl=ru

**Comment by rnyPlanet** [comment]
Thanks for the update. anyway, when watching, the speed resets every 10-30 seconds

**Comment by IvanSavoskin** [comment]
> Thanks for the update. anyway, when watching, the speed resets every 30seconds-1min. only the error is no longer visible in the logs( (previously it was possible to understand what was wrong and where)

Please clarify what extension settings you have enabled?
Does any playback rate reset or a specific one?

Is the video running in the feed, in media or in a dialog?

Perhaps this will help reproduce the problem
You can also try enabling debug mode in the console to display more detailed information about the extension's operation.

**Comment by rnyPlanet** [comment]
yes, this problem was on my side due to the old "more boosty". 
thanks for the updates
