### ISSUE TITLE
Добавить смайлы 7TV, BTTV или дать возможность добавлять локальные и кастомные

### ISSUE THREAD

**Issue by neolex1991** [IvanSavoskin/more-boosty-remastered#40]
### Description

По дефолту в чате трансляции на Boosty очень мало смайлов (даже в плане эмодзи). Если была бы возможность как-то прикрутить 7TV и/или BTTV было бы куда приятнее.

### Current version

1.2.2

### Browser

Chrome

**Comment by IvanSavoskin** [comment]
Добрый день
Подобный функционал не добавить нормально расширением. Это должны внедрять сами разработчики Boosty
Если даже добавлять это с помощью расширения, то нормально это будет работать только у тех, кто установил себе расширение
Поэтому не вижу смысла добавлять подобный функционал
